"""
Institutional PDF Report Generator for The Ultimate Edge by Noeman
Generates comprehensive printable PDF dossiers and summary tables containing 100% of scanner outputs.
"""

import io
import time
from typing import Optional, List, Dict
import pandas as pd
from reportlab.lib.pagesizes import letter, landscape, portrait
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def get_report_styles():
    """Build institutional typography and color styles."""
    styles = getSampleStyleSheet()
    
    custom_styles = {
        'MainTitle': ParagraphStyle(
            'MainTitle',
            parent=styles['Normal'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#1E1B4B'),
            fontName='Helvetica-Bold',
            alignment=1
        ),
        'SubTitle': ParagraphStyle(
            'SubTitle',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#4338CA'),
            fontName='Helvetica-Bold',
            alignment=1
        ),
        'MetaStyle': ParagraphStyle(
            'MetaStyle',
            parent=styles['Normal'],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor('#64748B'),
            alignment=1
        ),
        'CardHeader': ParagraphStyle(
            'CardHeader',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.white,
            fontName='Helvetica-Bold'
        ),
        'SectionHeader': ParagraphStyle(
            'SectionHeader',
            parent=styles['Normal'],
            fontSize=9,
            leading=11,
            textColor=colors.HexColor('#1E1B4B'),
            fontName='Helvetica-Bold'
        ),
        'ParamLabel': ParagraphStyle(
            'ParamLabel',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#475569'),
            fontName='Helvetica-Bold'
        ),
        'ParamValue': ParagraphStyle(
            'ParamValue',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#0F172A')
        ),
        'BullValue': ParagraphStyle(
            'BullValue',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#16A34A'),
            fontName='Helvetica-Bold'
        ),
        'BearValue': ParagraphStyle(
            'BearValue',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#DC2626'),
            fontName='Helvetica-Bold'
        ),
        'OptionValue': ParagraphStyle(
            'OptionValue',
            parent=styles['Normal'],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#2563EB'),
            fontName='Helvetica-Bold'
        ),
        'RationaleText': ParagraphStyle(
            'RationaleText',
            parent=styles['Normal'],
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor('#334155'),
            fontName='Helvetica-Oblique'
        ),
        'TableHeader': ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontSize=7.5,
            leading=9,
            textColor=colors.white,
            fontName='Helvetica-Bold'
        ),
        'TableCell': ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontSize=7,
            leading=8.5,
            textColor=colors.HexColor('#0F172A')
        )
    }
    return custom_styles

def generate_pdf_report(
    df: pd.DataFrame,
    title: str = "Institutional NSE Trade Setups Report",
    subtitle: str = "Generated by Institutional Analytics Engine",
    mode: str = "Daily",
    universe: str = "NSE Universe",
    report_type: str = "dossier" # 'dossier' (all details) or 'table' (summary)
) -> bytes:
    """
    Generate comprehensive in-memory PDF report with 100% of scanner output data.
    """
    buffer = io.BytesIO()
    st_dict = get_report_styles()
    
    # Use landscape for wide dossiers and summary tables
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(letter),
        leftMargin=24,
        rightMargin=24,
        topMargin=20,
        bottomMargin=20
    )
    
    elements = []
    
    # ─── 1. Document Title & Header ──────────────────────────────────────────
    elements.append(Paragraph("👑 The Ultimate Edge by Noeman", st_dict['MainTitle']))
    elements.append(Spacer(1, 3))
    elements.append(Paragraph(f"{title} — {subtitle}", st_dict['SubTitle']))
    elements.append(Spacer(1, 3))
    gen_time = time.strftime('%Y-%m-%d %H:%M:%S IST')
    elements.append(Paragraph(
        f"Scan Mode: <b>{mode}</b> | Universe: <b>{universe}</b> | Timestamp: <b>{gen_time}</b> | Setups Found: <b>{len(df)}</b>",
        st_dict['MetaStyle']
    ))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#4338CA'), spaceBefore=1, spaceAfter=8))
    
    if df.empty:
        elements.append(Paragraph("No trade setups or records found for this scan.", st_dict['ParamValue']))
    else:
        # ─── 2. DETAILED DOSSIER CARDS (Contains ALL Output Fields) ───────────
        for idx, row in df.iterrows():
            ticker = str(row.get('Ticker', '—'))
            name = str(row.get('Name', ticker))
            sector = str(row.get('Sector', 'NSE Equities / F&O'))
            
            # Live Price & Change
            close_p = row.get('Close', row.get('Current_Price', row.get('Entry_Price', 0.0)))
            chg_p = row.get('Change%', row.get('Chg%', 0.0))
            close_str = f"₹{float(close_p):,.2f}" if isinstance(close_p, (int, float)) and close_p > 0 else "—"
            chg_str = f"{float(chg_p):+.2f}%" if isinstance(chg_p, (int, float)) else str(chg_p)
            
            # Signal / Direction / Status
            signal = str(row.get('Signal', row.get('Action', row.get('Direction', row.get('Status', 'NEUTRAL')))))
            pattern_or_wave = str(row.get('Pattern', row.get('Wave_Stage', row.get('Setup_Pattern', row.get('Setup_Type', 'Standard Setup')))))
            timeframe = str(row.get('Timeframe', mode))
            conviction = str(row.get('Conviction', row.get('Probability', row.get('Early_Confirmation', 'High Conviction'))))
            
            # Trade Plan
            entry = row.get('Entry', row.get('Trigger_Entry', row.get('Entry_Price', close_p)))
            sl = row.get('Stop_Loss', row.get('SL', row.get('Invalidation_SL', 0.0)))
            t1 = row.get('Target_1', row.get('T1', row.get('Target_1_4Pct', 0.0)))
            t2 = row.get('Target_2', row.get('T2', row.get('Target_2_7Pct', 0.0)))
            rr = str(row.get('RR_Ratio', row.get('Risk_Reward', row.get('Option_RR', '1:3.0'))))
            time_cycle = str(row.get('Time_Cycle', row.get('Time to Target', '⚡ 1 - 3 Sessions')))
            
            # Option Strategy
            opt_action = str(row.get('Option_Action', row.get('Option_Strike', '—')))
            opt_expiry = str(row.get('Option_Expiry', 'Monthly Expiry'))
            opt_roi = str(row.get('Option_Target_ROI', '+100% to +300% ROI'))
            opt_sl = str(row.get('Option_SL', '-35% SL'))
            
            # Indicators
            rsi_val = str(row.get('RSI', '—'))
            adx_val = str(row.get('ADX', '—'))
            score_val = str(row.get('Composite_Score', row.get('Score', '—')))
            rationale = str(row.get('Rationale', row.get('How_It_Happened', row.get('Setup_Rationale', ''))))
            
            # Header color based on bullish/bearish
            is_bull = any(w in signal.upper() for w in ['BUY', 'BULL', 'LONG'])
            is_bear = any(w in signal.upper() for w in ['SELL', 'BEAR', 'SHORT'])
            hdr_bg = colors.HexColor('#166534') if is_bull else (colors.HexColor('#991B1B') if is_bear else colors.HexColor('#1E1B4B'))
            
            # Card Top Header Bar Table
            hdr_left = Paragraph(f"<b>{idx+1}. {ticker}</b> — {name} <font size='7' color='#CBD5E1'>({sector})</font>", st_dict['CardHeader'])
            hdr_mid = Paragraph(f"<b>Live Quote: {close_str} ({chg_str})</b>", st_dict['CardHeader'])
            hdr_right = Paragraph(f"<b>{signal} | {conviction}</b>", st_dict['CardHeader'])
            
            hdr_table = Table([[hdr_left, hdr_mid, hdr_right]], colWidths=[270, 180, 240])
            hdr_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), hdr_bg),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ]))
            
            # Detailed 3-Column Info Matrix
            col1_content = [
                [Paragraph("<b>🎯 SPOT / CASH TRADE PLAN</b>", st_dict['SectionHeader']), ""],
                [Paragraph("Timeframe:", st_dict['ParamLabel']), Paragraph(timeframe, st_dict['ParamValue'])],
                [Paragraph("Pattern / Wave:", st_dict['ParamLabel']), Paragraph(pattern_or_wave, st_dict['ParamValue'])],
                [Paragraph("Trigger Entry:", st_dict['ParamLabel']), Paragraph(f"₹{float(entry):,.2f}" if isinstance(entry, (int, float)) else str(entry), st_dict['BullValue'] if is_bull else st_dict['BearValue'])],
                [Paragraph("Invalidation SL:", st_dict['ParamLabel']), Paragraph(f"₹{float(sl):,.2f}" if isinstance(sl, (int, float)) else str(sl), st_dict['BearValue'])],
                [Paragraph("Target 1 (Base):", st_dict['ParamLabel']), Paragraph(f"₹{float(t1):,.2f}" if isinstance(t1, (int, float)) else str(t1), st_dict['BullValue'])],
                [Paragraph("Target 2 (Runner):", st_dict['ParamLabel']), Paragraph(f"₹{float(t2):,.2f}" if isinstance(t2, (int, float)) else str(t2), st_dict['BullValue'])],
                [Paragraph("Risk:Reward (R:R):", st_dict['ParamLabel']), Paragraph(f"<b>{rr}</b>", st_dict['ParamValue'])],
                [Paragraph("Target Timing:", st_dict['ParamLabel']), Paragraph(time_cycle, st_dict['ParamValue'])],
            ]
            
            col2_content = [
                [Paragraph("<b>⚡ WALL STREET OPTION PLAY</b>", st_dict['SectionHeader']), ""],
                [Paragraph("Option Action:", st_dict['ParamLabel']), Paragraph(opt_action, st_dict['OptionValue'])],
                [Paragraph("Recommended Expiry:", st_dict['ParamLabel']), Paragraph(opt_expiry, st_dict['ParamValue'])],
                [Paragraph("Expected ROI:", st_dict['ParamLabel']), Paragraph(opt_roi, st_dict['OptionValue'])],
                [Paragraph("Option Stop Loss:", st_dict['ParamLabel']), Paragraph(opt_sl, st_dict['BearValue'])],
                [Paragraph("RSI Momentum (14):", st_dict['ParamLabel']), Paragraph(str(rsi_val), st_dict['ParamValue'])],
                [Paragraph("ADX Trend Strength:", st_dict['ParamLabel']), Paragraph(str(adx_val), st_dict['ParamValue'])],
                [Paragraph("Composite Score:", st_dict['ParamLabel']), Paragraph(str(score_val), st_dict['ParamValue'])],
                [Paragraph("Trading Directive:", st_dict['ParamLabel']), Paragraph(f"<b>{signal}</b>", st_dict['BullValue'] if is_bull else st_dict['BearValue'])],
            ]
            
            t_col1 = Table(col1_content, colWidths=[95, 140])
            t_col1.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 1.5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 1.5),
                ('LEFTPADDING', (0, 0), (-1, -1), 3),
                ('RIGHTPADDING', (0, 0), (-1, -1), 3),
                ('SPAN', (0, 0), (1, 0)),
                ('LINEBELOW', (0, 0), (1, 0), 0.5, colors.HexColor('#CBD5E1')),
            ]))
            
            t_col2 = Table(col2_content, colWidths=[105, 135])
            t_col2.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('TOPPADDING', (0, 0), (-1, -1), 1.5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 1.5),
                ('LEFTPADDING', (0, 0), (-1, -1), 3),
                ('RIGHTPADDING', (0, 0), (-1, -1), 3),
                ('SPAN', (0, 0), (1, 0)),
                ('LINEBELOW', (0, 0), (1, 0), 0.5, colors.HexColor('#CBD5E1')),
            ]))
            
            # Column 3: Rationale / Narrative
            col3_content = [
                [Paragraph("<b>📖 SETUP ANATOMY & RATIONALE</b>", st_dict['SectionHeader'])],
                [Paragraph(rationale if rationale else "High-confluence multi-timeframe technical trigger meeting strict volatility compression and momentum expansion rules.", st_dict['RationaleText'])],
            ]
            t_col3 = Table(col3_content, colWidths=[200])
            t_col3.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('TOPPADDING', (0, 0), (-1, -1), 1.5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 1.5),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
                ('LINEBELOW', (0, 0), (-1, 0), 0.5, colors.HexColor('#CBD5E1')),
            ]))
            
            # Combine 3 Columns into Card Body
            body_table = Table([[t_col1, t_col2, t_col3]], colWidths=[240, 245, 205])
            body_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ]))
            
            card_flowables = [hdr_table, body_table, Spacer(1, 7)]
            elements.append(KeepTogether(card_flowables))
            
    # ─── 3. Disclaimer Footer ────────────────────────────────────────────────
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(
        "⚠️ <b>Institutional Disclaimer:</b> <i>Prepared strictly for reference, educational and analytical purposes by The Ultimate Edge by Noeman. Capital markets involve financial risk. Adhere strictly to the defined Invalidation Stop Loss levels and position sizing models.</i>",
        st_dict['MetaStyle']
    ))
    
    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
